version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot-im
    container_name: bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - BOT_TOKEN=""
      - OPENAI_API_KEY=""

      - DB_NAME="default_db"
      - DB_USER="gen_user"
      - DB_PORT="5432"
      - DB_HOST="localhost"
      - DB_PASS="postgres"

      - REDIS_HOST="localhost"
      - REDIS_PORT="6379"

      - AMPLITUDE_API_KEY=""

    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=default_db
      - POSTGRES_USER=gen_user
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:7 
    container_name: redis 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 


volumes:
  postgres_data:
  redis_data:  